name: s3-static-depl

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build Gatsby App
        run: npm install && npm run build && npm run deploy
        env:
          PRISMIC_REPO_NAME: ${{secrets.PRISMIC_REPO_NAME}}
          PRISMIC_ACCESS_TOKEN: ${{secrets.PRISMIC_ACCESS_TOKEN}}
          PRISMIC_CUSTOM_TYPES_API_TOKEN: ${{secrets.PRISMIC_CUSTOM_TYPES_API_TOKEN}}
          S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
