name: s3-static-depl

on:
  push:
    branches:
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy/
        with:
          PRISMIC_REPO_NAME: ${{secrets.PRISMIC_REPO_NAME}}
          PRISMIC_ACCESS_TOKEN: ${{secrets.PRISMIC_ACCESS_TOKEN}}
          PRISMIC_CUSTOM_TYPES_API_TOKEN: ${{secrets.PRISMIC_CUSTOM_TYPES_API_TOKEN}}
          S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_STAGING_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_STAGING_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
